name: image_gallery_saver
description: A new flutter plugin project for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 1.6.2
author: quicey <quiceyxu@gmail.com>
homepage: https://github.com/hui-z/image_gallery_saver

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.imagegallerysaver
    pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

