name: image_gallery_saver
description: A flutter plugin for save image to gallery, iOS need to add the following keys to your Info.plist file.
version: 2.0.1
homepage: https://github.com/hui-z/image_gallery_saver

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.imagegallerysaver
        pluginClass: ImageGallerySaverPlugin
      ios:
        pluginClass: ImageGallerySaverPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter

